book/urls.py
from django.urls import path, re_path
from . import views

app_name = "book"
pathpatterns = [

]

devops/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('hello/', include("hello.urls")),
    path('polls/', include("polls.urls")),
    path('user/',  include("user.urls")),
]

hello/urls.py
from django.urls import path, re_path
from . import views

# 普通传参 url 基本和无参数一样
    # 访问方法：http://IP:PORT/date/?year=2019&month=06
    # path("", views.date, name="date"),

    # 关键字传参   (?<参数名>参数类型)  在视图中直接通过参数名获取值
    # 访问方法：http://IP:PORT/date/2019/06/
    # re_path("(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/", views.date, name="date"),

    # 位置匹配
    # 访问方法： http://IP:PORT/date/2019/06/
    # re_path('([0-9]{4})/([0-9]{2})/', views.date, name="date"),


app_name = 'hello'

urlpatterns = [
    # path('hello', views.index, name='index'),
    path('',  views.userlist,  name='list'),
    path('create/', views.create, name="create"),
    path('edit/', views.edit, name='edit')


]

hello/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    SEX = (
        ('0', '男'),
        ('1', '女')
    )

    name = models.CharField(max_length=20, help_text='用户名')
    sex = models.IntegerField(choices=SEX, null=True, blank=True)
    password = models.CharField(max_length=32, help_text="密码")

    def __str__(self):
        return self.name

hello/views.py
from django.shortcuts import render, get_object_or_404, Http404
from django.http import HttpResponse, QueryDict
from .models import User

# Create your views here.

def create(request):
    date = request.POST
    name = date.get("name")
    sex = date.get('sex')
    passwd = date.get("passwd")

    # user = User.objects.create(name=name, sex=sex, password=passwd)

    return render(request, "hello/create.html")

def delet(request):
    pass

def edit(request):

    return render(request, "hello/edit.html")

def userlist(request):
    users = User.objects.all()
    return render(request, 'hello/userlist.html', {'users': users})

def results(request, user_id):
    try:
        user = User.objects.get(ok=user_id)
    except User.DoesNotExist:
        raise Http404("用户创建失败")
    else:
        return render(request, 'hello/results.html', {"message": "用户创建成功"})







# 普通传参 url 基本和无参数一样
# def date(request):
#     year = request.GET.get("year", "2019")
#     month = request.GET.get("month", "04")
#
#     return HttpResponse("year is {}, month is {}".format(year, month))


# 关键字传参   (?<参数名>参数类型)  在视图中直接通过参数名获取值
# def date(request, **kwargs):
#     print(kwargs)
#     year = kwargs.get('year', '2017')
#     month = kwargs.get('month', '01')
#
#     return HttpResponse("year is {}, month is {}".format(year, month))


# 位置匹配
# def date(request, year='1998', month='01'):
#     print("year = {}, month = {}".format(year, month))
#     return HttpResponse("year is {}, month is {}".format(year, month))

# def date(request):
#     print(request.scheme)
#     print(request.method)
#     print(request.headers)
#     print(request.path)
#     print(request.META)
#     print(request.GET)
#
#     date = request.GET
#     year = date.get("year", "1111")
#     month = date.get("month", "11")
#     print('===' * 30)
#
#     if request.method == 'POST':
#         print(request.method)
#         print(request.body)
#         print(QueryDict(request.body).dict())
#         print(request.POST)
#
#         date = request.POST
#         year = date.get("year", '2222')
#         month = date.get('month', '22')
#
#     return HttpResponse('year is {}, month is {}'.format(year, month))

templates/hello/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>自动化运维平台</title>
</head>
<body>

<p style="background-color: yellow;">
    {% block title%} 用户列表 {% endblock %}
</p>

{%block content%}
{% endblock%}

<p style="background-color: red;">版权所有： XXXXXX </p>

</body>
</html>

templates/hello/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
</head>
<body>
    <p>创建用户</p>

    <form action="{% url 'hello:create' %}" method="post">
        {% csrf_token %}

        <label for="name">用户名:</label>
        <input type="text" name="name" id="name"></br>

        <label for="passwd">密码 :</label>
        <input type="password" name="passwd" id="passwd"></br>

        <label for="sex">性别:</label>
        <input type="radio" name="sex" id="sex" value="0">男
        <input type="radio" name="sex" id="sex" value="1">女</br>

        <input type="submit", value="create">

    </form>
</body>
</html>

templates/hello/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit</title>
</head>
<body>
    <p>edit user id {{ user_id }}</p>
</body>
</html>

templates/hello/hello.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title>DevOps</title>
</head>
<body>
<!--<p>{{ name }}</p>-->

<!--<li>{{ books.0 }}</li>-->
<!--<li>{{ books.1 }}</li>-->
<!--<li>{{ books.2 }}</li>-->

<!--<div color = blue>hello my name is {{ user.name }} </br>-->
<!--    my age is {{ user.age }}-->
<!--</div>-->
<!--==========================================================================-->
<!--{% if user %}-->
<!--    <p> name: {{ user.name }}</p>-->
<!--{% else %}-->
<!--    <p> 用户不存在 </p>-->
<!--{% endif %}-->

<!--{% for book in books %}-->
<!--    <li>{{ book }}</li>-->
<!--{% endfor%}-->

<!--{% for user in userlist %}-->
<!--    <li>{{user.name}} -&ndash;&gt;  {{user.age}}}</li>-->
<!--{% endfor%}-->

<!--==========================================================================-->

<p>{{ classname}}</p>
{%for book in books%}
    <li> {{book}} </li>
{%endfor%}

<div style="background:wheat;color:bule;">
    {% for user in userlist %}
        <li>
            hello my name is {{user.name}} </br>
            my age is {{user.age}}
        </li>
    {% endfor %}
</div>

</body>
</html>

templates/hello/info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/hello/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Results</title>
</head>
<body>
    <p><strong>{{ messages }}}</strong></p>
</body>
</html>

templates/hello/userlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>自动化运维平台</title>
</head>
<body>
{% extends "hello/base.html" %}
{% block content %}

<a href="{% url 'hello:create' %}">创建用户</a>
<!--<a href="./create.html">创建用户</a>-->

<table border="1">
    <thead>
        <tr>
            <th>用户名</th>
            <th>姓名</th>
            <th>年龄</th>
            <th>操作</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td>{{ user.name }}</td>
            <td>{{ user.sex }}</td>
            <td>{{ user.password }}</td>
            <td><a>修改</a> </td>
            <td><a>删除</a></td>

        {% endfor %}
        </tr>
    </tbody>
</table>
{% endblock %}

</body>
</html>