book/urls.py
from django.urls import path, re_path
from . import views

app_name = "book"
pathpatterns = [

]

devops/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('hello/', include("hello.urls")),
    path('polls/', include("polls.urls")),
    path('user/',  include("user.urls")),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"
urlpatterns = [
    path('', views.userList, name='index'),
    path('userlist', views.userList, name='userlist'),
    path('useradd/', views.userAdd, name="useradd"),
    path('<int:user_id>/resetUser', views.setUser, name="setuser"),
    path('<int:user_id>/delUseer/', views.delUser, name='deluser'),
]

user/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    SEX = (
        (0, '男'),
        (1, "女")
    )

    name = models.CharField(max_length=20, help_text="用户名")
    password = models.CharField(max_length=32, help_text="密码")
    sex = models.IntegerField(choices=SEX, null=True, blank=True)

    def __str__(self):
        return self.name

user/views.py
from django.shortcuts import render, get_object_or_404, Http404
from .models import User
from django.views.generic import View

# Create your views here.
def userList(request):
    kw = request.GET.get("kw", "")
    users = User.objects.all()
    if kw:
        users = User.objects.filter(name__icontains=kw)
    return render(request, 'user/list.html', {'users': users, 'kw': kw})

def userAdd(request):
    msg = {}
    print(request.method)
    if request.method == "POST":
        date = request.POST.dict()
        # print(date)
        # print(date['sex'], type(date["sex"]))
        try:
            User.objects.create(**date)
            msg = {"code": 0, "result": "添加用户成功"}
        except:
            msg = {"code": 1, "errmsg": "添加用户失败"}
        return render(request, "user/results.html", {'msg': msg})

    return render(request, "user/useradd.html")


def setUser(request, **kwargs):
    msg = {}
    pk = kwargs.get("user_id")
    print(pk)
    try:
        user = User.objects.get(pk=pk)
        print(user)
    except User.DoesNotExist:
        raise Http404

    if request.method == 'POST':
        date = request.POST.dict()
        try:
            User.objects.filter(pk=pk).update(**date)
            msg = {'code': 0, 'result': "修改成功"}
        except:
            msg = {'code': 1, 'errmsg': "修改失败"}
        return render(request, "user/results.html", {'msg': msg})

    return render(request, "user/set.html", {'user': user, "msg": msg})

def delUser(request, **kwargs):
    msg = {}
    print(kwargs)
    pk = kwargs.get("user_id")
    try:
        user = User.objects.get(pk=pk)
    except User.DoesNotExist:
        raise Http404

    if request.method == "POST":
        try:
            User.objects.filter(pk=pk).delete()
            msg = {'code': 0, "result": "删除用户成功"}
        except:
            msg = {'code': 1, "errmsg": "删除用户失败"}
        return render(request, "user/results.html", {'msg': msg})

    return render(request, "user/delete.html", {"user": user, "msg": msg})

templates/user/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
</head>
<body>
    <h1>是否删除用户 {{ user.name }}</h1>
    <form method="post">
        <button type="submit">确定</button>
        <button><a href="{% url 'user:userlist' %}">取消</a></button>
    </form>

</body>
</html>

templates/user/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User List</title>
</head>
<body>
    <h1>用户列表</h1>
    <form action="{% url 'user:userlist' %}">
        <input type="text" name="kw" value="{{ kw }}" placeholder="请输入关键字">
        <button type="submit">搜索</button>
    </form>

    <table border="1">
        <thead>
                <tr>
                    <th>ID</th>
                    <th>用户名</th>
                    <th>密码</th>
                    <th>性别</th>
                    <th>修改</th>
                    <th>删除</th>
                </tr>

        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.password }}</td>
                {% if user.sex == 0 %}
                    <td>男</td>
                {% elif user.sex == 1 %}
                    <td>女</td>
                {% else %}
                    <td>未知</td>
                {% endif %}
                <td><a href="{% url 'user:setuser' user.id %}">修改</a> </td>
                <td><a href="{% url 'user:deluser' user.id %}">删除</a> </td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
    <a href="{% url 'user:useradd' %}">创建用户</a>
</body>
</html>

templates/user/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Results</title>
</head>
<body>
    {% if msg.code == 0 %}
        <p style="color: green">{{ msg.result }}</p>
    {% else %}
        <p style="color: red">{{ msg.errmsg }}</p>
    {% endif %}

    <a href="{% url 'user:useradd' %}">创建用户</a></br>
    <a href="{% url 'user:userlist' %}">返回用户列表</a>
</body>
</html>

templates/user/set.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Set User </title>
</head>
<body>
    <form action="" method="post">

        用户名：
        <input type="text" name="name" id="name" value="{{ user.name}}"></br>

        密码：
        <input type="password" name="password", id="password" value="{{ user.password }}"></br>

        性别：
        {% if user.sex == 0 %}
            <input type="radio" name="sex", id="sex" value=0 checked/>男
            <input type="radio" name="sex", id="sex" value=1 />女</br>
        {% else %}
            <input type="radio" name="sex", id="sex" value=0 />男
            <input type="radio" name="sex", id="sex" value=1 checked/>女</br>
        {% endif %}

        <input type="submit" value="修改">
    </form>
</body>
</html>

templates/user/useradd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
</head>
<body>
    <form action="" method="post">

        用户名：
        <input type="text" name="name" id="name"></br>

        密码：
        <input type="password" name="password", id="password"></br>

<!--        <label for="sex">性别：</label>-->
        性别：
        <input type="radio" name="sex", id="sex" value=0 checked/>男
        <input type="radio" name="sex", id="sex" value=1 />女</br>

        <input type="submit" value="create">
    </form>
</body>
</html>